/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import Builder.SuplementoBuilder;
import controller.PaqueteController;
import controller.SuplementoController;
import decorator.Paquete;
import dto.SuplementoDTO;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import strategy.EstrategiaOrdenamiento;
import strategy.OrdenPorIdAscendente;
import strategy.OrdenPorMarcaAlfabetica;
import strategy.OrdenPorPrecioAscendente;
import strategy.OrdenPorStockDescendente;


/**
 *
 * @author bran-
 */
public class VentanaSuplementos extends javax.swing.JFrame {

    /**
     * Creates new form VentanaSuplementos
     */
    private final SuplementoController suplementoController;

    public VentanaSuplementos() {
        initComponents();
        suplementoController = new SuplementoController();
        tablaSuplementos.setModel(new DefaultTableModel(
                new Object[]{"ID", "Nombre", "Descripción", "Tipo", "Marca", "Precio", "Stock", "Fecha"},
                0
        ));

        actualizarTablaSuplementos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fecha = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        txtIDSuplementos = new javax.swing.JTextField();
        txtNombreSuplementos = new javax.swing.JTextField();
        txtDescripcionSuplementos = new javax.swing.JTextField();
        txtTipoSuplementos = new javax.swing.JTextField();
        txtMarcaSuplementos = new javax.swing.JTextField();
        txtPrecioSuplementos = new javax.swing.JTextField();
        txtStockSuplementos = new javax.swing.JTextField();
        btnAgregarSuppleStock = new javax.swing.JButton();
        btnEditarSuppleStock = new javax.swing.JButton();
        btnBuscarSuppleStock = new javax.swing.JButton();
        btnAtrasSuppleStock = new javax.swing.JButton();
        btnEliminarSuppleStock = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSuplementos = new javax.swing.JTable();
        cmbOrdenamiento = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        btnVerPromocion = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtDescipc = new javax.swing.JTextField();
        txtPrecioFinal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SuppleStock", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Shree Devanagari 714", 1, 24))); // NOI18N

        jLabel1.setText("ID");

        jLabel2.setText("Nombre");

        jLabel3.setText("Descripcion");

        jLabel4.setText("Tipo");

        jLabel5.setText("Marca");

        jLabel6.setText("Precio");

        jLabel7.setText("Stock");

        jLabel8.setText("Fecha");

        btnAgregarSuppleStock.setText("Agregar ✔");

        btnEditarSuppleStock.setText("Editar ⚙️");
        btnEditarSuppleStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarSuppleStockActionPerformed(evt);
            }
        });

        btnBuscarSuppleStock.setText("Buscar 🔎");
        btnBuscarSuppleStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarSuppleStockActionPerformed(evt);
            }
        });

        btnAtrasSuppleStock.setText("Atras 🔙 ");

        btnEliminarSuppleStock.setText("Eliminar 🆑");
        btnEliminarSuppleStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarSuppleStockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(84, 84, 84)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(fecha, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                                        .addComponent(txtIDSuplementos)
                                                        .addComponent(txtStockSuplementos))
                                                    .addComponent(txtNombreSuplementos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(txtDescripcionSuplementos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtTipoSuplementos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtMarcaSuplementos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtPrecioSuplementos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(btnAgregarSuppleStock, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEliminarSuppleStock)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnEditarSuppleStock, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnBuscarSuppleStock, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAtrasSuppleStock, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnAtrasSuppleStock)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIDSuplementos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombreSuplementos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescripcionSuplementos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTipoSuplementos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMarcaSuplementos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecioSuplementos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStockSuplementos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarSuppleStock)
                    .addComponent(btnEditarSuppleStock)
                    .addComponent(btnAgregarSuppleStock))
                .addGap(18, 18, 18)
                .addComponent(btnEliminarSuppleStock)
                .addGap(15, 15, 15))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Shree Devanagari 714", 1, 24))); // NOI18N

        tablaSuplementos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaSuplementos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cmbOrdenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(cmbOrdenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Promociones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Shree Devanagari 714", 1, 24))); // NOI18N

        btnVerPromocion.setText("Ver Promoción");
        btnVerPromocion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPromocionActionPerformed(evt);
            }
        });

        jLabel9.setText("Descripción:");

        jLabel10.setText("Precio Final:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnVerPromocion, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(75, 75, 75)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDescipc)
                    .addComponent(txtPrecioFinal, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVerPromocion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtDescipc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPrecioFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarSuppleStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarSuppleStockActionPerformed
        try {
            LocalDate fechaRegistro = fecha.getDate()
                    .toInstant()
                    .atZone(ZoneId.systemDefault())
                    .toLocalDate();

            SuplementoDTO suplemento = new SuplementoBuilder()
                    .conNombre(txtNombreSuplementos.getText())
                    .conDescripcion(txtDescripcionSuplementos.getText())
                    .conTipo(txtTipoSuplementos.getText())
                    .conMarca(txtMarcaSuplementos.getText())
                    .conPrecio(Double.parseDouble(txtPrecioSuplementos.getText()))
                    .conStock(Integer.parseInt(txtStockSuplementos.getText()))
                    .conFechaRegistro(fechaRegistro)
                    .build();

            boolean registrado = suplementoController.registrarSuplemento(suplemento);
            if (registrado) {
                JOptionPane.showMessageDialog(this, "Suplemento registrado exitosamente");
                limpiarCampos();
                actualizarTablaSuplementos();
            } else {
                JOptionPane.showMessageDialog(this, "Error al registrar suplemento");
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Datos inválidos: " + e.getMessage());
        }
    }//GEN-LAST:event_btnAgregarSuppleStockActionPerformed

    private void btnBuscarSuppleStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarSuppleStockActionPerformed
        try {
            int id = Integer.parseInt(txtIDSuplementos.getText());

            SuplementoDTO suplemento = suplementoController.buscarSuplementoPorId(id);

            if (suplemento != null) {
                txtNombreSuplementos.setText(suplemento.getNombre());
                txtDescripcionSuplementos.setText(suplemento.getDescripcion());
                txtTipoSuplementos.setText(suplemento.getTipo());
                txtMarcaSuplementos.setText(suplemento.getMarca());
                txtPrecioSuplementos.setText(String.valueOf(suplemento.getPrecio()));
                txtStockSuplementos.setText(String.valueOf(suplemento.getStock()));

                java.util.Date fechaS = java.sql.Date.valueOf(suplemento.getFechaRegistro());
                fecha.setDate(fechaS);
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró un suplemento con ese ID.");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID inválido: " + e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al buscar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarSuppleStockActionPerformed

    private void btnVerPromocionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPromocionActionPerformed
        mostrarPromocionDeSuplementoSeleccionado();
    }//GEN-LAST:event_btnVerPromocionActionPerformed

    private void btnEliminarSuppleStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarSuppleStockActionPerformed
        try {
            int id = Integer.parseInt(txtIDSuplementos.getText());

            int opcion = JOptionPane.showConfirmDialog(this,
                    "¿Estás segura de eliminar el suplemento con ID " + id + "?",
                    "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

            if (opcion == JOptionPane.YES_OPTION) {
                boolean eliminado = suplementoController.eliminarSuplemento(id);

                if (eliminado) {
                    JOptionPane.showMessageDialog(this, "Suplemento eliminado correctamente.");
                    limpiarCampos();
                    actualizarTablaSuplementos();
                } else {
                    JOptionPane.showMessageDialog(this, "No se encontró el suplemento o no se pudo eliminar.");
                }
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID inválido.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
        }

    }//GEN-LAST:event_btnEliminarSuppleStockActionPerformed

    private void btnEditarSuppleStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarSuppleStockActionPerformed
        try {
            int id = Integer.parseInt(txtIDSuplementos.getText()); // Asegúrate de tener este campo visible o editable

            SuplementoDTO suplementoActualizado = new SuplementoBuilder()
                    .conId(id)
                    .conNombre(txtNombreSuplementos.getText())
                    .conDescripcion(txtDescripcionSuplementos.getText())
                    .conTipo(txtTipoSuplementos.getText())
                    .conMarca(txtMarcaSuplementos.getText())
                    .conPrecio(Double.parseDouble(txtPrecioSuplementos.getText()))
                    .conStock(Integer.parseInt(txtStockSuplementos.getText()))
                    .conFechaRegistro(((java.util.Date) fecha.getDate()).toInstant().atZone(ZoneId.systemDefault()).toLocalDate())
                    .build();

            boolean actualizado = suplementoController.actualizarSuplemento(suplementoActualizado);

            if (actualizado) {
                JOptionPane.showMessageDialog(this, "Suplemento actualizado correctamente.");
                limpiarCampos();

            } else {
                JOptionPane.showMessageDialog(this, "No se pudo actualizar el suplemento.");
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al actualizar: " + e.getMessage());
        }

    }//GEN-LAST:event_btnEditarSuppleStockActionPerformed

    public void limpiarCampos() {
        txtDescripcionSuplementos.setText("");
        txtIDSuplementos.setText("");
        txtMarcaSuplementos.setText("");
        txtNombreSuplementos.setText("");
        txtPrecioSuplementos.setText("");
        txtStockSuplementos.setText("");
        txtTipoSuplementos.setText("");
        fecha.setDate(null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaSuplementos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaSuplementos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaSuplementos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaSuplementos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaSuplementos().setVisible(true);
            }
        });
    }

    private void mostrarPromocionDeSuplementoSeleccionado() {
        try {
            int fila = tablaSuplementos.getSelectedRow();
            if (fila < 0) {
                JOptionPane.showMessageDialog(this, "Selecciona un suplemento primero", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            SuplementoDTO suplemento = new SuplementoDTO();
            suplemento.setId(Integer.parseInt(tablaSuplementos.getValueAt(fila, 0).toString()));
            suplemento.setNombre(tablaSuplementos.getValueAt(fila, 1).toString());
            suplemento.setTipo(tablaSuplementos.getValueAt(fila, 3).toString());
            suplemento.setMarca(tablaSuplementos.getValueAt(fila, 4).toString());
            suplemento.setPrecio(Double.parseDouble(tablaSuplementos.getValueAt(fila, 5).toString()));
            suplemento.setStock(Integer.parseInt(tablaSuplementos.getValueAt(fila, 6).toString()));

            Paquete paquete = new PaqueteController().generarPaqueteDesdeSuplemento(suplemento);

            txtDescipc.setText(paquete.getDescripcion());
            txtPrecioFinal.setText(String.format("$%.2f", paquete.getPrecio()));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al mostrar promoción: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void actualizarTablaSuplementos() {
        try {
            DefaultTableModel model = (DefaultTableModel) tablaSuplementos.getModel();
            model.setRowCount(0);

            ArrayList<SuplementoDTO> lista = suplementoController.obtenerTodos();

            for (SuplementoDTO sup : lista) {
                model.addRow(new Object[]{
                    sup.getId(),
                    sup.getNombre(),
                    sup.getDescripcion(),
                    sup.getTipo(),
                    sup.getMarca(),
                    sup.getPrecio(),
                    sup.getStock(),
                    sup.getFechaRegistro()
                });
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al cargar los suplementos: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    private void ordenarSuplementos() {
        String seleccion = cmbOrdenamiento.getSelectedItem().toString();

        EstrategiaOrdenamiento estrategia = null;

        switch (seleccion) {
            case "Orden original (por ID)":
                estrategia = new OrdenPorIdAscendente();
                break;
            case "Precio Ascendente":
                estrategia = new OrdenPorPrecioAscendente();
                break;
            case "Stock Descendente":
                estrategia = new OrdenPorStockDescendente();
                break;
            case "Marca Alfabética":
                estrategia = new OrdenPorMarcaAlfabetica();
                break;
        }
         SuplementoController controller = new SuplementoController();
        ArrayList<SuplementoDTO> listaOrdenada = controller.obtenerOrdenados(estrategia);

        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new Object[]{"ID", "Nombre", "Descripción", "Tipo", "Marca", "Precio", "Stock", "Fecha de Registro"});

        for (SuplementoDTO sup : listaOrdenada) {
            modelo.addRow(new Object[]{
                sup.getId(),
                sup.getNombre(),
                sup.getDescripcion(),
                sup.getTipo(),
                sup.getMarca(),
                sup.getPrecio(),
                sup.getStock(),
                sup.getFechaRegistro()
            });
        }

        tablaSuplementos.setModel(modelo);
    }
    
    private void configurarOrdenamiento() {
        cmbOrdenamiento.addItem("Orden original (por ID)");
        cmbOrdenamiento.addItem("Precio Ascendente");
        cmbOrdenamiento.addItem("Stock Descendente");
        cmbOrdenamiento.addItem("Marca Alfabética");

        cmbOrdenamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenarSuplementos();
            }
        });

        cmbOrdenamiento.setSelectedIndex(0);
        ordenarSuplementos();
    }

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarSuppleStock;
    private javax.swing.JButton btnAtrasSuppleStock;
    private javax.swing.JButton btnBuscarSuppleStock;
    private javax.swing.JButton btnEditarSuppleStock;
    private javax.swing.JButton btnEliminarSuppleStock;
    private javax.swing.JButton btnVerPromocion;
    private javax.swing.JComboBox<String> cmbOrdenamiento;
    private com.toedter.calendar.JDateChooser fecha;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaSuplementos;
    private javax.swing.JTextField txtDescipc;
    private javax.swing.JTextField txtDescripcionSuplementos;
    private javax.swing.JTextField txtIDSuplementos;
    private javax.swing.JTextField txtMarcaSuplementos;
    private javax.swing.JTextField txtNombreSuplementos;
    private javax.swing.JTextField txtPrecioFinal;
    private javax.swing.JTextField txtPrecioSuplementos;
    private javax.swing.JTextField txtStockSuplementos;
    private javax.swing.JTextField txtTipoSuplementos;
    // End of variables declaration//GEN-END:variables
}
