/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import Builder.SuplementoBuilder;
import controller.SuplementoController;
import dto.SuplementoDTO;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bran-
 */
public class VentanaSuplementos extends javax.swing.JFrame {

    /**
     * Creates new form VentanaSuplementos
     */
    private final SuplementoController suplementoController;

    public VentanaSuplementos() {
        initComponents();
        suplementoController = new SuplementoController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fecha = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        txtIDSuplementos = new javax.swing.JTextField();
        txtNombreSuplementos = new javax.swing.JTextField();
        txtDescripcionSuplementos = new javax.swing.JTextField();
        txtTipoSuplementos = new javax.swing.JTextField();
        txtMarcaSuplementos = new javax.swing.JTextField();
        txtPrecioSuplementos = new javax.swing.JTextField();
        txtStockSuplementos = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSuplementos = new javax.swing.JTable();
        btnAgregarSuppleStock = new javax.swing.JButton();
        btnEditarSuppleStock = new javax.swing.JButton();
        btnBuscarSuppleStock = new javax.swing.JButton();
        btnAtrasSuppleStock = new javax.swing.JButton();
        btnEliminarSuppleStock = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("SuppleStock"));

        jLabel1.setText("ID");

        jLabel2.setText("Nombre");

        jLabel3.setText("Descripcion");

        jLabel4.setText("Tipo");

        jLabel5.setText("Marca");

        jLabel6.setText("Precio");

        jLabel7.setText("Stock");

        jLabel8.setText("Fecha");

        tablaSuplementos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaSuplementos);

        btnAgregarSuppleStock.setText("Agregar ✔");

        btnEditarSuppleStock.setText("Editar ⚙️");
        btnEditarSuppleStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarSuppleStockActionPerformed(evt);
            }
        });

        btnBuscarSuppleStock.setText("Buscar 🔎");
        btnBuscarSuppleStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarSuppleStockActionPerformed(evt);
            }
        });

        btnAtrasSuppleStock.setText("Atras 🔙 ");

        btnEliminarSuppleStock.setText("Eliminar 🆑");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAtrasSuppleStock, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(84, 84, 84)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(fecha, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                                        .addComponent(txtIDSuplementos)
                                                        .addComponent(txtStockSuplementos))
                                                    .addComponent(txtNombreSuplementos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(txtDescripcionSuplementos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtTipoSuplementos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtMarcaSuplementos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtPrecioSuplementos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(btnAgregarSuppleStock, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEliminarSuppleStock)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnEditarSuppleStock, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnBuscarSuppleStock, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnAtrasSuppleStock)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtIDSuplementos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombreSuplementos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDescripcionSuplementos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTipoSuplementos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMarcaSuplementos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrecioSuplementos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStockSuplementos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarSuppleStock)
                    .addComponent(btnEditarSuppleStock)
                    .addComponent(btnAgregarSuppleStock))
                .addGap(18, 18, 18)
                .addComponent(btnEliminarSuppleStock)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarSuppleStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarSuppleStockActionPerformed
        try {
            int id = Integer.parseInt(txtIDSuplementos.getText());

            SuplementoDTO suplemento = suplementoController.buscarSuplementoPorId(id);

            if (suplemento != null) {
                txtNombreSuplementos.setText(suplemento.getNombre());
                txtDescripcionSuplementos.setText(suplemento.getDescripcion());
                txtTipoSuplementos.setText(suplemento.getTipo());
                txtMarcaSuplementos.setText(suplemento.getMarca());
                txtPrecioSuplementos.setText(String.valueOf(suplemento.getPrecio()));
                txtStockSuplementos.setText(String.valueOf(suplemento.getStock()));

                java.util.Date fechaS = java.sql.Date.valueOf(suplemento.getFechaRegistro());
                fecha.setDate(fechaS);
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró un suplemento con ese ID.");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID inválido: " + e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al buscar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarSuppleStockActionPerformed


    private void btnVerPromocionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPromocionActionPerformed
        mostrarPromocionDeSuplementoSeleccionado();
    }//GEN-LAST:event_btnVerPromocionActionPerformed

    private void btnEliminarSuppleStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarSuppleStockActionPerformed
        try {
            int id = Integer.parseInt(txtIDSuplementos.getText());

            int opcion = JOptionPane.showConfirmDialog(this,
                    "¿Estás segura de eliminar el suplemento con ID " + id + "?",
                    "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

            if (opcion == JOptionPane.YES_OPTION) {
                boolean eliminado = suplementoController.eliminarSuplemento(id);

                if (eliminado) {
                    JOptionPane.showMessageDialog(this, "Suplemento eliminado correctamente.");
                    limpiarCampos();
                    actualizarTablaSuplementos();
                } else {
                    JOptionPane.showMessageDialog(this, "No se encontró el suplemento o no se pudo eliminar.");
                }
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID inválido.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
        }

    }//GEN-LAST:event_btnEliminarSuppleStockActionPerformed

    private void btnEditarSuppleStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarSuppleStockActionPerformed
        try {
            int id = Integer.parseInt(txtIDSuplementos.getText()); // Asegúrate de tener este campo visible o editable

            SuplementoDTO suplementoActualizado = new SuplementoBuilder()
                    .conId(id)
                    .conNombre(txtNombreSuplementos.getText())
                    .conDescripcion(txtDescripcionSuplementos.getText())
                    .conTipo(txtTipoSuplementos.getText())
                    .conMarca(txtMarcaSuplementos.getText())
                    .conPrecio(Double.parseDouble(txtPrecioSuplementos.getText()))
                    .conStock(Integer.parseInt(txtStockSuplementos.getText()))
                    .conFechaRegistro(((java.util.Date) fecha.getDate()).toInstant().atZone(ZoneId.systemDefault()).toLocalDate())
                    .build();

            boolean actualizado = suplementoController.actualizarSuplemento(suplementoActualizado);

            if (actualizado) {
                JOptionPane.showMessageDialog(this, "Suplemento actualizado correctamente.");
                limpiarCampos();

            } else {
                JOptionPane.showMessageDialog(this, "No se pudo actualizar el suplemento.");
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al actualizar: " + e.getMessage());
        }

    }//GEN-LAST:event_btnEditarSuppleStockActionPerformed


    public void limpiarCampos() {
        txtDescripcionSuplementos.setText("");
        txtIDSuplementos.setText("");
        txtMarcaSuplementos.setText("");
        txtNombreSuplementos.setText("");
        txtPrecioSuplementos.setText("");
        txtStockSuplementos.setText("");
        txtTipoSuplementos.setText("");
        fecha.setDate(null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaSuplementos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaSuplementos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaSuplementos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaSuplementos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaSuplementos().setVisible(true);
            }
        });
    }


    private void mostrarPromocionDeSuplementoSeleccionado() {
        try {
            int fila = tablaSuplementos.getSelectedRow();
            if (fila < 0) {
                JOptionPane.showMessageDialog(this, "Selecciona un suplemento primero", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            SuplementoDTO suplemento = new SuplementoDTO();
            suplemento.setId(Integer.parseInt(tablaSuplementos.getValueAt(fila, 0).toString()));
            suplemento.setNombre(tablaSuplementos.getValueAt(fila, 1).toString());
            suplemento.setTipo(tablaSuplementos.getValueAt(fila, 3).toString());
            suplemento.setMarca(tablaSuplementos.getValueAt(fila, 4).toString());
            suplemento.setPrecio(Double.parseDouble(tablaSuplementos.getValueAt(fila, 5).toString()));
            suplemento.setStock(Integer.parseInt(tablaSuplementos.getValueAt(fila, 6).toString()));

            Paquete paquete = new PaqueteController().generarPaqueteDesdeSuplemento(suplemento);

            txtDescipc.setText(paquete.getDescripcion());
            txtPrecioFinal.setText(String.format("$%.2f", paquete.getPrecio()));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al mostrar promoción: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void actualizarTablaSuplementos() {
        try {
            DefaultTableModel model = (DefaultTableModel) tablaSuplementos.getModel();
            model.setRowCount(0);

            ArrayList<SuplementoDTO> lista = suplementoController.obtenerTodos();

            for (SuplementoDTO sup : lista) {
                model.addRow(new Object[]{
                    sup.getId(),
                    sup.getNombre(),
                    sup.getDescripcion(),
                    sup.getTipo(),
                    sup.getMarca(),
                    sup.getPrecio(),
                    sup.getStock(),
                    sup.getFechaRegistro()
                });
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al cargar los suplementos: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarSuppleStock;
    private javax.swing.JButton btnAtrasSuppleStock;
    private javax.swing.JButton btnBuscarSuppleStock;
    private javax.swing.JButton btnEditarSuppleStock;
    private javax.swing.JButton btnEliminarSuppleStock;
    private com.toedter.calendar.JDateChooser fecha;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaSuplementos;
    private javax.swing.JTextField txtDescripcionSuplementos;
    private javax.swing.JTextField txtIDSuplementos;
    private javax.swing.JTextField txtMarcaSuplementos;
    private javax.swing.JTextField txtNombreSuplementos;
    private javax.swing.JTextField txtPrecioSuplementos;
    private javax.swing.JTextField txtStockSuplementos;
    private javax.swing.JTextField txtTipoSuplementos;
    // End of variables declaration//GEN-END:variables
}
